### ISSUE TITLE
You might as well try doom

### ISSUE THREAD

**Issue by elais** [evantravers/ThingsToOrgmode#1]
If you're going to give org-mode a try I feel like you might as well give doom emacs a go. If I had to describe it as anything I would say its a more complete vim emulation layer for emacs that tries to fill in the blanks left by evil (and much more). I'm a ~~very~~ minor contributor to the project but I saw this in my feed and figured I'd throw it out there for you.

**Comment by evantravers** [comment]
Elais!

Long time no see! I have poked into Doom a couple times… I have it on one of my laptops. I’m still at the “learning what is emacs, what is doom, what is org” stage, so poking around with bare emacs and org mode, but I’ll likely play with it some more. Thanks for the recommendation!
